services:
  # 1. Backend (FastAPI)
  app:
    build: .
    container_name: medical_history_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/medical_db

  # 2. Base de datos (MongoDB)
  mongo:
    image: mongo:latest
    container_name: medical_history_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Frontend (HTML + JS)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: medical_history_frontend
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  mongo_data:
